### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Description 1"
}
###
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "Category 1",
    "type": 2
}

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/14a80b9c-fac6-4253-a331-8ad18305e42c