version: '3'
services:
  app:
    build: .
    command: bash -c "npm install && tail -f /dev/null"
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    #   - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
